main_app/urls.py
from django.urls import path
from .views import TreatListCreate, TreatDelete
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_reportcard/', views.add_reportcard, name='add_reportcard'),
    path('dogs/<int:dog_id>/reportcard_detail/<int:reportcard_id>/', views.reportcard_detail, name='reportcard_detail'),
    path('dogs/<int:pk>/reportcard_update/<int:reportcard_id>/', views.ReportCardUpdate.as_view(), name='reportcard_update'),
    path('dogs/<int:pk>/reportcard_delete/<int:reportcard_id>/', views.ReportCardDelete.as_view(), name='reportcard_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('treats/', views.TreatListCreate.as_view(), name='treats_index'),
    path('treats/<int:pk>/delete/', TreatDelete.as_view(), name='treat_delete'), 
    path('dogs/<int:dog_id>/assoc_treat/<int:treat_id>/', views.assoc_treat, name='assoc_treat'),
    path('dogs/<int:dog_id>/unassoc_treat/<int:treat_id>/', views.unassoc_treat, name='unassoc_treat'),
    path('dogs/<int:dog_id>/add_photo/', views.add_photo, name='add_photo'),
]

pawfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Treat(models.Model):
    name = models.CharField(max_length=50)
    flavor = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        permissions = [
            ("create_treat", "Can create treat"),
            ("remove_treat", "Can delete treat"),
        ]


class Dog(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    breed = models.CharField(max_length=50)
    weight = models.IntegerField()
    diet = models.TextField(max_length=250)
    vaccinated = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    treats = models.ManyToManyField(Treat)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})


GRADES = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('F', 'F'),
)

class ReportCard(models.Model):
    date = models.DateField()
    behavior = models.TextField(max_length=250)
    summary = models.TextField(max_length=250)
    grade = models.CharField(
        max_length=1,
        choices=GRADES,
        default=GRADES[0][0]
    )
    fed = models.BooleanField(default=True)
    photo_url = models.URLField(blank=True)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_grade_display()} on {self.date}'
    
    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    reportcard = models.ForeignKey(ReportCard, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'Photo for dog_id: {self.dog_id} @{self.url}'

main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import ReportCard, Treat

class ReportCardForm(ModelForm):
    photo_file = forms.ImageField(required=False)
    class Meta:
        model = ReportCard
        fields = ['date', 'behavior', 'summary', 'fed', 'grade']


# CIRCLE BACK - ADDING DOG TREAT ON DOG INDEX PAGE
class TreatForm(ModelForm):
    class Meta:
        model = Treat
        fields = ['name', 'flavor']
#  -------------------------------

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User, Permission
from django.urls import reverse, reverse_lazy
from .models import Dog, Treat, Photo, ReportCard
from .forms import ReportCardForm, TreatForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')


# Dog Functions
@login_required
def dogs_index(request):
    dogs = Dog.objects.filter(user=request.user)
    return render(request, 'dogs/index.html', {
      'dogs' : dogs
    })

@login_required
def dogs_detail(request, dog_id):
  dog = Dog.objects.get(id=dog_id)
  id_list = dog.treats.all().values_list('id')
  treats_dog_doesnt_have = Treat.objects.exclude(id__in=id_list)
  reportcard_form = ReportCardForm()
  return render(request, 'dogs/detail.html', {
    'dog': dog, 'reportcard_form': reportcard_form,
    'treats': treats_dog_doesnt_have
    })

class DogCreate(LoginRequiredMixin, CreateView):
  model = Dog
  fields = ['name', 'breed', 'age', 'weight', 'diet', 'vaccinated']
  
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class DogUpdate(LoginRequiredMixin, UpdateView):
  model = Dog
  fields = ['breed', 'age', 'weight', 'diet', 'vaccinated']

class DogDelete(LoginRequiredMixin, DeleteView):
  model = Dog
  success_url = '/dogs'


# Report Card Functions
@login_required
def add_reportcard(request, dog_id):
    dog = Dog.objects.get(id=dog_id)

    if request.method == 'POST':
        form = ReportCardForm(request.POST, request.FILES)
        if form.is_valid():
            new_reportcard = form.save(commit=False)
            new_reportcard.dog = dog

            photo_file = request.FILES.get('photo_file')
            if photo_file:
                s3 = boto3.client('s3')
                key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
                try:
                    bucket = os.environ['S3_BUCKET']
                    s3.upload_fileobj(photo_file, bucket, key)
                    url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                    new_reportcard.photo_url = url
                except Exception as e:
                    print('An error occurred uploading file to S3')
                    print(e)

            new_reportcard.save()
            return redirect('reportcard_detail', dog_id=dog_id, reportcard_id=new_reportcard.id)
    else:
        form = ReportCardForm()

    return render(request, 'dogs/reportcard_form.html', {
        'dog': dog,
        'reportcard_form': form
    })

@login_required
def reportcard_detail(request, dog_id, reportcard_id):
    dog = Dog.objects.get(id=dog_id)
    reportcard = ReportCard.objects.get(id=reportcard_id)

    return render(request, 'dogs/reportcard_detail.html', {
        'reportcard': reportcard, 
        'dog': dog,
    })

class ReportCardUpdate(LoginRequiredMixin, UpdateView):
  model = ReportCard
  fields = ['date', 'behavior', 'summary', 'fed', 'grade']
  template_name = 'dogs/reportcard_form.html'

  def get_success_url(self):
        return reverse('detail', args=[str(self.kwargs['pk'])])

  def get_object(self, queryset=None):
        # Get the dog's primary key from the URL
        dog_pk = self.kwargs.get('pk')

        # Get the reportcard_id from the URL
        reportcard_id = self.kwargs.get('reportcard_id')

        # Retrieve the specific ReportCard instance to update
        reportcard = ReportCard.objects.get(id=reportcard_id, dog__id=dog_pk)
        return reportcard

  def form_valid(self, form):
        # Save the form and update the ReportCard instance
        reportcard = form.save()
        return super().form_valid(form)

class ReportCardDelete(LoginRequiredMixin, DeleteView):
  model = ReportCard
  template_name = 'dogs/reportcard_confirm_delete.html'
  
  def get_success_url(self):
    return reverse('detail', kwargs={'dog_id': self.kwargs['pk']})
  
  def get_object(self, queryset=None):
        # Get the dog's primary key from the URL
        dog_pk = self.kwargs.get('pk')

        # Get the reportcard_id from the URL
        reportcard_id = self.kwargs.get('reportcard_id')

        # Retrieve the specific ReportCard instance to update
        reportcard = ReportCard.objects.get(id=reportcard_id, dog__id=dog_pk)
        return reportcard
  
  def get_context_data(self, **kwargs):
    # Use super function to access and call methods of the parent class (DeleteView)
    # This ensures we can add customizations to the context without overriding or negating
      # the default behavior of the parent class (DeleteView)
    context = super().get_context_data(**kwargs)
    # Retrieve the correct Dog instance
    context['dog'] = Dog.objects.get(pk=self.kwargs['pk'])  
    return context


# Treat Functions
class TreatListCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView, ListView):
  model = Treat
  template_name = 'main_app/treat_list.html'
  form_class = TreatForm
  context_object_name = 'treat_list'
  success_url = '/treats/'
  permission_required = 'main_app.create_treat'

class TreatDelete(PermissionRequiredMixin, DeleteView):
  model = Treat
  success_url = reverse_lazy('treats_index')
  permission_required = 'main_app.remove_treat'

def treat_create_delete(request):
    avg_user = request.user.has_perm('main_app.remove_treat')
    treat_list = Treat.objects.all()  # Retrieve your treats
    
    context = {
        'treat_list': treat_list,
        'avg_user' : avg_user,
    }

    return render(request, 'main_app/treat_list.html', context)

@login_required
def assoc_treat(request, dog_id, treat_id):
    Dog.objects.get(id=dog_id).treats.add(treat_id)
    return redirect('detail', dog_id=dog_id)  

@login_required
def unassoc_treat(request, dog_id, treat_id):
    Dog.objects.get(id=dog_id).treats.remove(treat_id)
    return redirect('detail', dog_id=dog_id)  


# Signup
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


# Add Photo
def add_photo(request, dog_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, dog_id=dog_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
    return redirect('detail', dog_id=dog_id)


# Get the desired permissions
create_treat_perm = Permission.objects.get(codename='create_treat')
remove_treat_perm = Permission.objects.get(codename='remove_treat')

# Assign permissions to a user
non_staff_users = User.objects.filter(is_staff=False)

for user in non_staff_users:
  user.user_permissions.remove(create_treat_perm, remove_treat_perm)
  
# Assign permissions to a user
staff_users = User.objects.filter(is_staff=True)

for user in staff_users:
  user.user_permissions.add(create_treat_perm, remove_treat_perm)

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div id='dog-container'>
  <div id='dog-details'>
      <h2><img id="report-img" src="/static/css/images/ball.png">  {{ dog.name }}</h2>
      {% for photo in dog.photo_set.all %}
          <img id="avatar" src="{{photo.url}}">
      {% empty %}
          <p>No Photos Uploaded</p>
      {% endfor %}
      <br>
      <form action="{% url 'add_photo' dog.id %}" enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <input type="file" name="photo-file">
          <br><br>
          <button type="submit" class="btn">Upload Photo</button>
      </form>
      <p><strong>Age:</strong> {{dog.age}}</p>
      <p><strong>Breed:</strong> {{ dog.breed }}</p>
      <p><strong>Weight:</strong> {{ dog.weight }}</p>
      <p><strong>Diet and Feeding Instructions:</strong> {{ dog.diet }}</p>
      {% if dog.vaccinated %}
          <p><strong>Vaccines are up to date</strong></p>
      {% else %}
          <p><strong>Vaccines MUST be updated</strong></p>
      {% endif %}
      <a href="{% url 'dogs_update' dog.id %}">Edit</a> 
      |
      <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
  </div>
  <div id='report-card'>
    <h2><img id="report-img" src="/static/css/images/award.png"> Report Card</h2>
    <div id="card-back">
      <form id="report-form" action="{% url 'add_reportcard' dog.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ reportcard_form.as_p }}
          <input type="submit" class="btn" value="Add Report Card">
      </form>
    </div>
      <br>
      <hr>
      <table>
          <thead>
              <tr><th>Date</th><th>Grade</th></tr>
          </thead>
          <tbody>
              {% for reportcard in dog.reportcard_set.all %}
                  <tr>
                      <td>{{reportcard.date}}</td>
                      <td align="center">{{reportcard.get_grade_display}}</td>
                      <td><a href="{% url 'reportcard_detail' dog.id reportcard.id %}">View</a> | </td>
                      <td><a href="{% url 'reportcard_update' dog.id reportcard.id %}">Edit</a> | </td>
                      <td><a href="{% url 'reportcard_delete' dog.id reportcard.id %}">Delete</a></td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
    <div id='current-treats'>
        <h2><img id="report-img" src="/static/css/images/dog-food.png"> {{ dog.name }}'s Treats</h2>
        {% if dog.treats.count %}
          {% for treat in dog.treats.all %}
            <div id="treat">
              <p><img id="food-img" src="/static/css/images/bone.png"> {{ treat.name }}</p>
              <form action="{% url 'unassoc_treat' dog.id treat.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          {% endfor %}
          {% else %}
            <h5>No Treats Yet</h5>
          {% endif %}
    </div>
    <div id='av-treats'>
      <h2><img id="report-img" src="/static/css/images/dog-food.png">  Available Treats</h2>
        {% if treats.count %}
          {% for treat in treats.all %}
            <div id="treat">
              <p><img id="food-img" src="/static/css/images/bone.png">  {{ treat.name }}</p>
                <form action="{% url 'assoc_treat' dog.id treat.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn">Add</button>
                </form>
            </div>
          {% endfor %}
          {% else %}
            <h5>{{dog.name}}Already Has All Treats Available</h5>
          {% endif %}
    </div>      
</div>

{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
    <div id="dog-card">
        <h2>{{ dog.name }}</h2>
        <a id="detail-btn" href="{% url 'detail' dog.id %}">Details</a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/dogs/reportcard_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Report Card</h1>

<h4>Are you sure you want to delete this Report Card?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn">
    <a href="{% url 'detail' dog_id=dog.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/dogs/reportcard_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Report Card Details</h1>
<div id="rc-details">
    <div id="rc-box-1">
        {% if reportcard.photo_url %}
            <img id="dog-photo" src="{{ reportcard.photo_url }}" alt="{{ dog.name }}'s Photo">
        {% else %}
            <p>No photo available</p>
        {% endif %}
    </div>
    <div id="rc-box-2">
        <p><strong>Date:</strong> {{ reportcard.date }}</p>
        <p><strong>Behavior:</strong> {{ reportcard.behavior }}</p>
        <p><strong>Summary:</strong> {{ reportcard.summary }}</p>
        {% if reportcard.fed %}
            <p>{{ dog.name }} was fed</p>
        {% else %}
            <p>{{ dog.name }} was not fed</p>
        {% endif %}
        <p><strong>Grade:</strong> {{ reportcard.grade }}</p>
    </div>
</div>
{% endblock %}

main_app/templates/dogs/reportcard_details.html
{% extends 'base.html' %}
{% block content %}

<h2>Report Card Details</h2>
<p>Date: {{reportcard.date}}
<p>Behavior: {{ reportcard.behavior }}</p>
<p>Summary: {{ reportcard.summary }}</p>
{% if dog.fed %}
        <p>{{dog.name}} was fed</p>
        {% else %}
        <p>{{dog.name}} was not fed</p>
        {% endif %}
<p>Grade: {{ reportcard.grade }}</p>

{% endblock %}

main_app/templates/dogs/reportcard_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Report Card</h1>
    <form id="add-dog-form" action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }} 
        </table>
        <input type="submit" value="Submit" class="btn">
    </form>
{% endblock %}